version: '3.5'

networks:
  web:
    external: true

services:
  selenium-app:
    container_name: selenium-app
    hostname: selenium
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PHP_LATEST_VERSION: ${PHP_LATEST_VERSION}
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - ./:/var/www/src
      - ./docker/php/root:/root
    working_dir: /var/www/src
    networks:
      - web
    privileged: true
    shm_size: 4g

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: web-driver-chrome
    hostname: chrome
    networks:
      - web
    ports:
      - "5900:5900"
      - "4444:4444"
    privileged: true
    shm_size: 2g
